package com.example.funkidslearnsapp.game

import com.example.funkidslearnsapp.R

object LetterGameData {

    val games = listOf(
        LetterGameItem("CAT", R.drawable.cat, 1),
        LetterGameItem("BED", R.drawable.bed, 1),
        LetterGameItem("HOUSE", R.drawable.house, 2),
        LetterGameItem("SUN", R.drawable.sun, 1),
        LetterGameItem("DOG", R.drawable.dog, 2),
        LetterGameItem("TREE", R.drawable.tree, 1),
        LetterGameItem("WATER", R.drawable.water, 2),
        LetterGameItem("HAPPY", R.drawable.happy, 1),
        LetterGameItem("SMILE", R.drawable.smile, 2),
        LetterGameItem("BALL", R.drawable.ball, 2),
        LetterGameItem("BOOK", R.drawable.book, 2),
        LetterGameItem("CHAIR", R.drawable.chair, 2),
        LetterGameItem("TABLE", R.drawable.table, 3),
        LetterGameItem("APPLE", R.drawable.apple, 0),
        LetterGameItem("ORANGE", R.drawable.orange, 2),
        LetterGameItem("BANANA", R.drawable.banana, 1),
        LetterGameItem("GRAPES", R.drawable.grapes, 3),
        LetterGameItem("SCHOOL", R.drawable.school, 2),
        LetterGameItem("FRIEND", R.drawable.friend, 3),
        LetterGameItem("FAMILY", R.drawable.family, 1),
        LetterGameItem("BROTHER", R.drawable.brother, 2),
        LetterGameItem("SISTER", R.drawable.sister, 3),
        LetterGameItem("FATHER", R.drawable.father, 1),
        LetterGameItem("MOTHER", R.drawable.mother, 2),
        LetterGameItem("COMPUTER", R.drawable.computer, 3),
        LetterGameItem("KEYBOARD", R.drawable.keyboard, 2),
        LetterGameItem("MONITOR", R.drawable.monitor, 3),
        LetterGameItem("MOUSE", R.drawable.mouse, 2),
        LetterGameItem("PHONE", R.drawable.phone, 2),
        LetterGameItem("MUSIC", R.drawable.music, 2),
        LetterGameItem("VIDEO", R.drawable.video, 2),
        LetterGameItem("GAME", R.drawable.game, 2),
        LetterGameItem("FLOWER", R.drawable.flower, 2),
        LetterGameItem("GARDEN", R.drawable.garden, 3),
        LetterGameItem("GRASS", R.drawable.grass, 2),
        LetterGameItem("SKY", R.drawable.sky, 2),
        LetterGameItem("CLOUD", R.drawable.cloud, 2),
        LetterGameItem("RAIN", R.drawable.rain, 2),
        LetterGameItem("STORM", R.drawable.storm, 3),
        LetterGameItem("WIND", R.drawable.wind, 2),
        LetterGameItem("EARTH", R.drawable.earth, 2),
        LetterGameItem("PLANET", R.drawable.planet, 3),
        LetterGameItem("SPACE", R.drawable.space, 2),
        LetterGameItem("ROCKET", R.drawable.rocket, 3),
        LetterGameItem("MOON", R.drawable.moon, 2),
        LetterGameItem("STAR", R.drawable.star, 2)
    )
}
